# Site settings
title: Sahasra Iyer
description: "I&#39;m a &amp; software developer."
baseurl: "" 
# baseurl: /pahadiahimanshu
permalink: pretty
# url: "http://pahadiahimanshu.github.io"

# User settings
username: Sahasra Iyer
user_title: Lorem Ipsum - FrontEnd
email: sahasra2406@gmail.com
# twitter_username: Sahasra Iyer
# github_username:  pahadiahimanshu
# instagram_username:  pahadiahimanshu
profile_picture: https://68.media.tumblr.com/93f384858e9273d5b980b418e2f2f4d5/tumblr_o5i2aybLJG1uapsfmo2_250.png


exclude: ['README.md']
_markdown: kramdown
# theme: jekyll-theme-minimal

collections:
  projects:
    output: true
    permalink: /projects/:path